version: '3'
services:
  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ./bin/rails s -b 0.0.0.0

  db:
    image: postgres

  spring:
    build: .
    volumes:
      - .:/myapp
    command: ./bin/spring server
